;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-copy-region
        cua-paste
        cua-scroll-up
        indent-for-tab-command
        keyboard-escape-quit
        sgml-slash
        swiper
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-projectile-find-file
        cua-cancel
        cua-cut-region
        ))
